# Generated by Django 5.1.4 on 2025-01-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_adress_teacher_firma_adi_teacher_telephone2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('surname', models.CharField(max_length=255, verbose_name='surname')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('firma_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='firma_adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='telephone')),
                ('telephone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='telephone2')),
                ('mail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='mail')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='adress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
