# Generated by Django 5.1.4 on 2024-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_adress_teacher_telephone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
