# Generated by Django 5.1.4 on 2025-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='firma_adi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='firma_adi'),
        ),
    ]
