# Generated by Django 5.1.4 on 2024-12-19 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('statu', models.CharField(blank=True, max_length=255, null=True, verbose_name='statu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='start_date')),
                ('end_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='end_date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='file_name')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
