# Generated by Django 5.1.4 on 2024-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
