# Generated by Django 5.1.4 on 2025-01-11 16:41

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='statu',
        ),
        migrations.RemoveField(
            model_name='coursefile',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='dilekce_required',
            field=models.BooleanField(default=False, verbose_name='dilekce_required'),
        ),
        migrations.AddField(
            model_name='course',
            name='statu_erp',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_erp'),
        ),
        migrations.AddField(
            model_name='course',
            name='statu_pano',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_pano'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='description_1'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='description_2'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='description_3'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='dilekce_is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='dilekce_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='dilekce_name'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_1'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_2'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_3'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_olusturma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='egitim_olusturma_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinklik_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='etkinklik_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_aciklamasi',
            field=models.TextField(blank=True, null=True, verbose_name='etkinlik_aciklamasi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_adi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etkinlik_adi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etkinlik_no'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='gun_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gun_sayisi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='guncellenme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='guncellenme_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilimci_kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilimci_kodu'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilimci_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilimci_sayisi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilimcilar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilanlar'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kodu'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='ogretmen_adi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ogretmen_adi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sehir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sehir'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sinif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sinif'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sisteme_giris_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='sisteme_giris_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='statu_erp',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_erp'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='statu_pano',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_pano'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True, verbose_name='uploaded_date'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='uyari_date',
            field=models.DateField(blank=True, null=True, verbose_name='uyari_date'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='verilen_not',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='verilen_not'),
        ),
        migrations.CreateModel(
            name='CourseFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=courses.models.unique_file_path, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded_at')),
                ('course_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.coursefile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursefile',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_file', to='courses.coursefileversion', verbose_name='current_version'),
        ),
    ]
