# Generated by Django 5.1.4 on 2024-12-14 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='is_finish'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
