# Generated by Django 5.1.4 on 2024-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_finish_coursefile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='statu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='statu'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='file'),
        ),
    ]
