# Generated by Django 5.1.4 on 2024-12-25 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursefile_is_uploaded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='file',
        ),
        migrations.CreateModel(
            name='CourseFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='version_number')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded_at')),
                ('course_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.coursefile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursefile',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_file', to='courses.coursefileversion', verbose_name='current_version'),
        ),
    ]
