# Generated by Django 5.1.4 on 2025-01-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_statu_remove_coursefile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='uploaded_date',
        ),
    ]
