# Generated by Django 5.1.4 on 2024-12-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursefile_file_coursefileversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='dilekce_is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='dilekce_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='dilekce_name'),
        ),
    ]
