# Generated by Django 5.1.4 on 2024-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_statu_alter_coursefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_name'),
        ),
    ]
