# Generated by Django 5.1.4 on 2025-01-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursefile_uploaded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='is_uploaded',
        ),
    ]
