# Generated by Django 5.1.4 on 2024-12-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursefile_dilekce_is_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start_date'),
        ),
    ]
