# Generated by Django 5.1.4 on 2025-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursefile_is_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='end_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='end_year'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start_year'),
        ),
    ]
