# Generated by Django 5.1.4 on 2024-12-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursefile_end_date_coursefile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type'),
        ),
    ]
