# Generated by Django 5.1.4 on 2025-01-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='statu_erp',
        ),
    ]
