# Generated by Django 5.1.4 on 2024-12-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursefile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='statu',
            field=models.CharField(blank=True, choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], max_length=255, null=True, verbose_name='statu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='statu',
            field=models.CharField(blank=True, choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], max_length=255, null=True, verbose_name='statu'),
        ),
    ]
