# Generated by Django 5.1.4 on 2025-01-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursefile_statu_erp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='statu_erp',
        ),
    ]
