# Generated by Django 5.1.4 on 2025-01-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_statu_erp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='guncellenme_tarihi',
            new_name='guncelleme_tarihi',
        ),
    ]
