# Generated by Django 5.1.4 on 2024-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursefile_statu_alter_course_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='uploaded_at',
            field=models.DateField(blank=True, null=True, verbose_name='uploaded_at'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='statu',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu'),
        ),
    ]
