# Generated by Django 5.1.4 on 2025-01-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_guncellenme_tarihi_coursefile_guncelleme_tarihi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='etkinklik_tarihi',
            new_name='etkinlik_tarihi',
        ),
        migrations.RemoveField(
            model_name='coursefile',
            name='dilekce_is_uploaded',
        ),
    ]
