# Generated by Django 5.1.4 on 2024-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursefile_uploaded_at_alter_coursefile_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='course',
            name='dilekce_required',
            field=models.BooleanField(default=False, verbose_name='dilekce_required'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='description_1'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='description_2'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='description_3'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_1'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_2'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_kayit_no_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_kayit_no_3'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='egitim_olusturma_tarihi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='egitim_olusturma_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_adi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etkinlik_adi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etkinlik_kodu'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etkinlik_no'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilanlar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilanlar'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilimci_kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilimci_kodu'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sehir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sehir'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sinif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sinif'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sisteme_giris_tarihi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ekleme_tarihi'),
        ),
    ]
