# Generated by Django 5.1.4 on 2025-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_etkinklik_tarihi_coursefile_etkinlik_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='etkinlik_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='etkinlik_tarihi'),
        ),
    ]
