# Generated by Django 5.1.4 on 2024-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_uploaded_at_coursefile_uploaded_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='statu',
        ),
        migrations.AddField(
            model_name='coursefile',
            name='statu_erp',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_erp'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='statu_pano',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('iptal', 'İptal'), ('arsiv', 'Arşiv')], default='aktif', max_length=255, verbose_name='statu_pano'),
        ),
    ]
