# Generated by Django 5.1.4 on 2024-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_statu_course_statu_erp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='warning_message',
            field=models.TextField(blank=True, null=True, verbose_name='warning_message'),
        ),
    ]
