# Generated by Django 5.1.4 on 2024-12-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursefile_warning_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='warning_message',
        ),
    ]
