# Generated by Django 5.1.4 on 2024-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_coursefile_warning_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='etkinklik_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='etkinklik_tarihi'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='egitim_olusturma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='egitim_olusturma_tarihi'),
        ),
    ]
