# Generated by Django 5.1.4 on 2024-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursefile_etkinklik_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='ogretmen_adi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ogretmen_adi'),
        ),
    ]
