# Generated by Django 5.1.4 on 2024-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursefile_ogretmen_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='etkinlik_aciklamasi',
            field=models.TextField(blank=True, null=True, verbose_name='etkinlik_aciklamasi'),
        ),
    ]
