# Generated by Django 5.1.4 on 2024-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_coursefile_etkinlik_aciklamasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefile',
            old_name='katilanlar',
            new_name='katilimcilar',
        ),
        migrations.RemoveField(
            model_name='coursefile',
            name='etkinlik_kodu',
        ),
        migrations.AddField(
            model_name='coursefile',
            name='guncellenme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='guncellenme_tarihi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='katilimci_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='katilimci_sayisi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='kodu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kodu'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='verilen_not',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='verilen_not'),
        ),
    ]
