# Generated by Django 5.1.4 on 2024-12-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_katilanlar_coursefile_katilimcilar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefile',
            name='sisteme_giris_tarihi',
        ),
    ]
