# Generated by Django 5.1.4 on 2024-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_coursefile_sisteme_giris_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='sisteme_giris_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='sisteme_giris_tarihi'),
        ),
    ]
