# Generated by Django 5.1.4 on 2024-12-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursefile_sisteme_giris_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefileversion',
            name='version_number',
        ),
    ]
