# Generated by Django 5.1.4 on 2024-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_coursefileversion_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='gun_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gun_sayisi'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='uyari_date',
            field=models.DateField(blank=True, null=True, verbose_name='uyari_date'),
        ),
    ]
