# Generated by Django 5.1.4 on 2025-01-01 21:33

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursefile_gun_sayisi_coursefile_uyari_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefileversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.unique_file_path, verbose_name='file'),
        ),
    ]
