# Generated by Django 5.1.4 on 2025-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_coursefileversion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True, verbose_name='uploaded_date'),
        ),
    ]
