# Generated by Django 5.1.4 on 2024-12-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=255, verbose_name='Ders Adı')),
                ('durum', models.CharField(max_length=255, verbose_name='Durum')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dersi_veren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='DersBelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255, verbose_name='Kategori')),
                ('belge_adi', models.CharField(max_length=255, verbose_name='Belge Adı')),
                ('belge', models.FileField(upload_to='ders_belgeleri/', verbose_name='Belge')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders')),
            ],
        ),
    ]
