# Generated by Django 5.1.4 on 2024-12-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='baslik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='dersi_veren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Dersi Veren'),
        ),
        migrations.AlterField(
            model_name='dersbelgesi',
            name='ders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders', verbose_name='Ders'),
        ),
    ]
